-- ========================================================
-- Schema Database Peminjaman Buku Perpustakaan (Supabase)
-- Responsi PPB 2026
-- ========================================================

-- 1. Hapus tabel jika sudah ada sebelumnya
DROP TABLE IF EXISTS loans CASCADE;

-- 2. Buat tabel loans
CREATE TABLE loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_name VARCHAR(255) NOT NULL,
    member_code VARCHAR(50),
    book_title VARCHAR(255) NOT NULL,
    book_isbn VARCHAR(50),
    loan_date DATE NOT NULL DEFAULT CURRENT_DATE,
    due_date DATE NOT NULL,
    return_date DATE,
    status VARCHAR(50) NOT NULL DEFAULT 'Dipinjam',
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tambahkan constraint check untuk status yang valid
ALTER TABLE loans 
ADD CONSTRAINT check_loan_status 
CHECK (status IN ('Dipinjam', 'Kembali', 'Terlambat'));

-- 4. Pengaturan Row Level Security (RLS) di Supabase
-- Agar API dapat melakukan operasi CRUD secara bebas menggunakan Anon Key:
ALTER TABLE loans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" 
ON loans FOR SELECT 
USING (true);

CREATE POLICY "Allow public insert access" 
ON loans FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Allow public update access" 
ON loans FOR UPDATE 
USING (true) 
WITH CHECK (true);

CREATE POLICY "Allow public delete access" 
ON loans FOR DELETE 
USING (true);

-- (Opsi alternatif jika tidak ingin menggunakan RLS:
-- ALTER TABLE loans DISABLE ROW LEVEL SECURITY; )

-- 5. Data Awal (Dummy / Seed Data)
INSERT INTO loans (member_name, member_code, book_title, book_isbn, loan_date, due_date, return_date, status, notes)
VALUES
('Ahmad Fauzi', 'MBR-001', 'Clean Code: A Handbook of Agile Software Craftsmanship', '978-0132350884', '2026-09-10', '2026-09-17', '2026-09-16', 'Kembali', 'Buku dikembalikan dalam kondisi baik.'),
('Siti Nurhaliza', 'MBR-002', 'Design Patterns: Elements of Reusable Object-Oriented Software', '978-0201633610', '2026-09-15', '2026-09-22', NULL, 'Terlambat', 'Terlambat 9 hari, sudah dikirimkan pengingat email.'),
('Budi Santoso', 'MBR-003', 'Node.js Design Patterns - Third Edition', '978-1839214110', '2026-09-25', '2026-10-02', NULL, 'Dipinjam', 'Peminjaman reguler durasi 7 hari.'),
('Dewi Lestari', 'MBR-004', 'You Don''t Know JS Yet: Get Started', '978-1698296241', '2026-09-28', '2026-10-05', NULL, 'Dipinjam', 'Peminjaman pertama anggota baru.');
